# Resources/config/services.yml
services:

    webeweb.datatablesbundle.manager.datatables:
        class: WBW\Bundle\JQuery\DataTablesBundle\Manager\DataTablesManager

    webeweb.datatablesbundle.twig.extension.datatables:
        class: WBW\Bundle\JQuery\DataTablesBundle\Twig\Extension\DataTablesTwigExtension
        tags:
            - { name: "twig.extension" }
