# Resources/config/services.yml
services:

    webeweb.jquerydatatables.manager.datatables:
        class:  WBW\Bundle\JQuery\DataTablesBundle\Manager\DataTablesManager
        public: true

    webeweb.jquerydatatables.twig.extension.datatables:
        class:     WBW\Bundle\JQuery\DataTablesBundle\Twig\Extension\DataTablesTwigExtension
        arguments: ["@webeweb.bootstrap.twig.extension.renderer"]
        public:    true
        tags:
            - { name: "twig.extension" }
