# Resources/config/services.yml
services:

    webeweb.jquery_datatables.manager:
        class:  WBW\Bundle\JQuery\DataTablesBundle\Manager\DataTablesManager
        public: true

    webeweb.jquerydatatables.twig.extension:
        class:     WBW\Bundle\JQuery\DataTablesBundle\Twig\Extension\DataTablesTwigExtension
        arguments: ["@twig", "@webeweb.core.twig.extension.renderer"]
        public:    true
        tags:
            - { name: "twig.extension" }
