# Resources/config/routing/datatables.yml
jquery_datatables_delete:
    path:     "/datatables/{name}/delete/{id}"
    defaults: { _controller: "JQueryDataTablesBundle:DataTables:delete" }
    methods:  ["GET"]

jquery_datatables_export:
    path:     "/datatables/{name}/export"
    defaults: { _controller: "JQueryDataTablesBundle:DataTables:export" }
    methods:  ["GET"]

jquery_datatables_index:
    path:     "/datatables/{name}/index"
    defaults: { _controller: "JQueryDataTablesBundle:DataTables:index" }
    methods:  ["GET", "POST"]

jquery_datatables_options:
    path:     "/datatables/{name}/options"
    defaults: { _controller: "JQueryDataTablesBundle:DataTables:options" }
    methods:  ["GET"]

jquery_datatables_render:
    path:     "/datatables/{name}/render"
    defaults: { _controller: "JQueryDataTablesBundle:DataTables:render" }
    methods:  ["GET"]

jquery_datatables_show:
    path:     "/datatables/{name}/show/{id}"
    defaults: { _controller: "JQueryDataTablesBundle:DataTables:show" }
    methods:  ["GET"]
