# Resources/config/routing/datatables.yml
jquery_datatables_index:
    path:     /datatables/index/{name}
    defaults: { _controller: "JQueryDataTablesBundle:DataTables:index" }
    methods: [GET,POST]
