# Resources/config/routing/datatables.yml
jquery_datatables_index:
    path:     "/datatables/{name}/index"
    defaults: { _controller: "JQueryDataTablesBundle:DataTables:index" }
    methods:  ["GET", "POST"]
